name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Run Typecheck
        run: npm run typecheck

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: akoskm/saas:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Set your DigitalOcean access token as a secret in your repository settings

      - name: Deploy to DigitalOcean
        run: |
          # Replace <droplet-id> with your actual droplet ID and <tag> with the Docker image tag you want to deploy
          doctl compute droplet-action docker-image-replace ubuntu-s-1vcpu-2gb-fra1-01 akoskm/saas:latest --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
